function(forge_enable_sanitizers target)
    if(NOT FORGE_ENABLE_SANITIZERS)
        return()
    endif()
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        target_compile_options(${target} PRIVATE -fsanitize=address,undefined)
        target_link_options(${target} PRIVATE -fsanitize=address,undefined)
    else()
        message(WARNING "Sanitizers are not configured for this compiler")
    endif()
endfunction()

